AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - db/schema.rb
Metrics/AbcSize:
  Exclude:
    - db/**/*
    - app/models/ability.rb
    - app/controllers/users/registrations_controller.rb
    - spec/support/controller_helpers.rb

Metrics/LineLength:
  Exclude:
    - config/initializers/*
    - db/**/*
Metrics/MethodLength:
  Max: 10
  Exclude:
    - app/models/ability.rb
    - db/**/*

Style/GuardClause:
  Exclude:
    - app/models/ability.rb
    - app/controllers/home_controller.rb

Metrics/BlockLength:
  Exclude:
    - config/**/*
    - db/**/*
    - Guardfile
    - spec/**/*

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false
